export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_GIF = 'CREATE_GIF'
export const FETCH_GIFS = 'FETCH_GIFS'
export const FETCH_GIF = 'FETCH_GIF'
export const DELETE_GIF = 'DELETE_GIF'
export const EDIT_GIF = 'EDIT_GIF'